# Site settings
title: Julian Arnold
name: Julian Arnold

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/julianarnold96
 - title: LinkedIn
   url: https://www.linkedin.com/in/julian-arnold-aab381206/

#Any buzzword skills you want to include
skills:
 - Python
 - PL/SQL
 - Machine learning 
 - Data Science
 - Relational Databases


#Work experience is required
roles:
 - title: Intern / Working Student Analytics Data Provision
   start: 2017
   end: 2020
   employer: IDS GmbH
   description: 
   
#Education is required
education:
 - level: Master of Science (M.Sc.)
   date: 2020
   subject: Mathematics and Computer Science
   school: Technische Universit채t M체nchen (TUM)
 - level: Bachelor of Science (B.Sc.)
   date: 2018
   subject: Mathematics and Economics
   school: Technische Universit채t M체nchen (TUM)

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/specializations/algorithms
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - julianarnold96/DeepProC


intro: |
  I am a M.Sc. in Mathematics with a focus on data science. I have primarily focused my studies on machine learning, statistics, optimization and databases. <br/><br/>
  I enjoy building interesting machine learning models, with a cool application focus and a good emphasis on good engineering principles and clean code (having worked across differing languages, and different groups of people, I recognise that good code is contextual).<br/><br/>
  I have worked at IDS as an intern / working student in the analyitcs data provision team, where I was responsible for data cleaning and the automation of this very.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Python</strong>: In my Master's Thesis, I used Python as the primary language and have been building the data pipelines as well as the deep learning model in Python. I am familiar with a range of Python libraries, such as Pandas, NumPy, Scikit-learn, as well as PyTorch. </a>.<br/><br/>
   <strong>PL/SQL</strong>: I used PL/SQL on daily basis in my 3 years at IDS. I am experienced in querying and manipulating differnt databases, and implementing automated data manipulations along data processing pipelines. <br/><br/>
   <strong>R</strong>: I implemented my Bachelor's Thesis with R. I can build dataframes and linear / logistic regression models. <br/><br/>
   <strong>Machine Learning</strong>: Thanks to my Master's program, I have a solid backgroud on machine learning and data science. From the basics like SVMs, decision trees, k-nearest neighbors and simple feed-forward networks, to more advanced topics like attention and reinforcement learning.
   
